<?php

/**
 * @file
 * Contains webhooks.module..
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webhooks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webhooks module.
    case 'help.page.webhooks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_create().
 */
function webhooks_entity_create(EntityInterface $entity) {

}

/**
 * Implements hook_entity_update().
 */
function webhooks_entity_update(EntityInterface $entity) {

}

/**
 * Implements hook_entity_delete().
 */
function webhooks_entity_delete(EntityInterface $entity) {

}
