<?php

/**
 * @file
 * Contains webhooks.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webhooks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webhooks module.
    case 'help.page.webhooks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
