webhooks.webhook.*:
  type: config_entity
  label: 'Webhook config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    status:
      type: boolean
      label: 'Status'
    payload_url:
      type: string
      label: 'Payload URL'
    last_usage:
      type: integer
      label: 'Last usage of a Webhook'
    events:
      type: string
      label: 'Events'
    result:
      type: boolean
      label: 'Result'
    entity_type:
      type: string
      label: 'Entity Type'
    entity_id:
      type: integer
      label: 'Entity ID'
    secret:
      type: string
      label: 'Secret'
    content_type:
      type: string
      label: 'Content Type'



