<?php

namespace Drupal\webhooks\Exception;

use Drupal\Core\Entity\Exception;

/**
 * Class WebhookMismatchSignatureException
 * @package Drupal\webhooks\Exception
 */
class WebhookMismatchSignatureException extends \Exception {
  /**
   *  The signature which is received via header.
   *
   * @var
   */
  protected $signature_received;

  /**
   * The signature which is generated by the module.
   *
   * @var
   */
  protected $signature_generated;

  /**
   * MismatchSignatureException constructor.
   * @param $signature_received
   * @param $signature_generated
   */
  public function __construct($signature_received, $signature_generated) {
    $message = sprintf('The received signature %s does not match the generated signature %s.',
      $signature_received, $signature_generated);
    parent::__construct($message);
  }
}
